package wd;

public class Percona {

    public static void main(String[] args) {
        String[] lines = new String[] {
                "idx_seamless_templates_resources_updated_on ON seamless_templates_resources(updated_on);",
                "idx_transaction_ext_invoices_updated_on ON transaction_ext_invoices(updated_on);",
                "idx_transaction_api_transaction_status_updated_on ON transaction_api_transaction_status(updated_on);",
                "idx_transaction_ext_card_token_updated_on ON transaction_ext_card_token(updated_on);",
                "idx_merchant_account_provider_routes_updated_on ON merchant_account_provider_routes(updated_on);",
                "idx_multi_payments_notifications_updated_on ON multi_payments_notifications(updated_on);",
                "idx_seamless_templates_i18n_updated_on ON seamless_templates_i18n(updated_on);",
                "idx_users_updated_on ON users(updated_on);",
                "idx_user_role_updated_on ON user_role(updated_on);",
                "idx_seamless_templates_updated_on ON seamless_templates(updated_on);",
                "idx_transaction_ext_travel_updated_on ON transaction_ext_travel(updated_on);",
                "idx_travel_journeys_updated_on ON travel_journeys(updated_on);",
                "idx_multi_payments_statuses_updated_on ON multi_payments_statuses(updated_on);",
                "idx_merchant_account_provider_params_updated_on ON merchant_account_provider_params(updated_on);",
                "idx_transaction_in_progress_updated_on ON transaction_in_progress(updated_on);",
                "idx_transaction_ext_airline_updated_on ON transaction_ext_airline(updated_on);",
                "idx_transaction_ext_sub_merchant_info_updated_on ON transaction_ext_sub_merchant_info(updated_on);",
                "idx_transaction_ext_consumers_updated_on ON transaction_ext_consumers(updated_on);",
                "idx_transaction_ext_analytics_updated_on ON transaction_ext_analytics(updated_on);",
                "idx_transaction_ext_shippings_updated_on ON transaction_ext_shippings(updated_on);",
                "idx_transaction_ext_devices_updated_on ON transaction_ext_devices(updated_on);",
                "idx_transaction_alternate_ids_updated_on ON transaction_alternate_ids(updated_on);",
                "idx_transaction_ext_3d_updated_on ON transaction_ext_3d(updated_on);",
                "idx_billing_fees_updated_on ON billing_fees(updated_on);",
                "idx_dwh_batch_transfers_updated_on ON dwh_batch_transfers(updated_on);",
                "idx_dwh_transfer_validation_elements_updated_on ON dwh_transfer_validation_elements(updated_on);",
                "idx_dwh_transfer_validations_updated_on ON dwh_transfer_validations(updated_on);",
                "idx_feature_togglz_updated_on ON feature_togglz(updated_on);",
                "idx_installment_labels_updated_on ON installment_labels(updated_on);",
                "idx_merchant_account_ext_easypay_updated_on ON merchant_account_ext_easypay(updated_on);",
                "idx_merchant_account_provider_installment_plan_updated_on ON merchant_account_provider_installment_plan(updated_on);",
                "idx_merchant_account_resolvers_updated_on ON merchant_account_resolvers(updated_on);",
                "idx_merchant_account_transaction_type_mapping_updated_on ON merchant_account_transaction_type_mapping(updated_on);",
                "idx_merchant_account_velocities_updated_on ON merchant_account_velocities(updated_on);",
                "idx_merchant_categories_updated_on ON merchant_categories(updated_on);",
                "idx_merchant_customer_ext_wallets_updated_on ON merchant_customer_ext_wallets(updated_on);",
                "idx_merchant_data_keys_updated_on ON merchant_data_keys(updated_on);",
                "idx_mpi_acquirer_bins_updated_on ON mpi_acquirer_bins(updated_on);",
                "idx_mpi_merchant_accounts_updated_on ON mpi_merchant_accounts(updated_on);",
                "idx_multi_payment_transaction_types_updated_on ON multi_payment_transaction_types(updated_on);",
                "idx_multi_payments_flows_updated_on ON multi_payments_flows(updated_on);",
                "idx_multi_payments_merchant_flows_updated_on ON multi_payments_merchant_flows(updated_on);",
                "idx_persistence_queue_updated_on ON persistence_queue(updated_on);",
                "idx_provider_account_ext_rule_text_updated_on ON provider_account_ext_rule_text(updated_on);",
                "idx_provider_acquirers_updated_on ON provider_acquirers(updated_on);",
                "idx_provider_card_terminals_updated_on ON provider_card_terminals(updated_on);",
                "idx_provider_group_terminals_updated_on ON provider_group_terminals(updated_on);",
                "idx_provider_installment_plan_updated_on ON provider_installment_plan(updated_on);",
                "idx_provider_parameters_updated_on ON provider_parameters(updated_on);",
                "idx_provider_route_resolvers_updated_on ON provider_route_resolvers(updated_on);",
                "idx_provider_terminals_updated_on ON provider_terminals(updated_on);",
                "idx_provider_types_updated_on ON provider_types(updated_on);",
                "idx_providers_updated_on ON providers(updated_on);",
                "idx_proxytokenizer_apis_updated_on ON proxytokenizer_apis(updated_on);",
                "idx_psp_parameters_updated_on ON psp_parameters(updated_on);",
                "idx_psp_user_updated_on ON psp_user(updated_on);",
                "idx_psps_updated_on ON psps(updated_on);",
                "idx_raw_alipay_spot_pay_reconciliations_updated_on ON raw_alipay_spot_pay_reconciliations(updated_on);",
                "idx_raw_alipay_xborder_reconciliations_updated_on ON raw_alipay_xborder_reconciliations(updated_on);",
                "idx_raw_barzahlen_reconciliations_updated_on ON raw_barzahlen_reconciliations(updated_on);",
                "idx_raw_cb_states_updated_on ON raw_cb_states(updated_on);",
                "idx_raw_cbs_updated_on ON raw_cbs(updated_on);",
                "idx_raw_fimi_reconciliations_updated_on ON raw_fimi_reconciliations(updated_on);",
                "idx_raw_recon_states_updated_on ON raw_recon_states(updated_on);",
                "idx_raw_upop_disputes_updated_on ON raw_upop_disputes(updated_on);",
                "idx_raw_upop_reconciliations_updated_on ON raw_upop_reconciliations(updated_on);",
                "idx_raw_wpsl_cp_txs_updated_on ON raw_wpsl_cp_txs(updated_on);",
                "idx_release_notes_updated_on ON release_notes(updated_on);",
                "idx_risk_execution_cfg_updated_on ON risk_execution_cfg(updated_on);",
                "idx_roles_updated_on ON roles(updated_on);",
                "idx_seamless_resources_updated_on ON seamless_resources(updated_on);",
                "idx_sequences_updated_on ON sequences(updated_on);",
                "idx_scheme_regions_updated_on ON scheme_regions(updated_on);",
                "idx_transaction_ext_adjustment_updated_on ON transaction_ext_adjustment(updated_on);",
                "idx_transaction_ext_avs_updated_on ON transaction_ext_avs(updated_on);",
                "idx_transaction_ext_batch_close_updated_on ON transaction_ext_batch_close(updated_on);",
                "idx_transaction_ext_cabuy_updated_on ON transaction_ext_cabuy(updated_on);",
                "idx_transaction_ext_cbs_updated_on ON transaction_ext_cbs(updated_on);",
                "idx_transaction_ext_cruise_industry_updated_on ON transaction_ext_cruise_industry(updated_on);",
                "idx_transaction_ext_files_updated_on ON transaction_ext_files(updated_on);",
                "idx_transaction_ext_forex_updated_on ON transaction_ext_forex(updated_on);",
                "idx_transaction_ext_hotel_updated_on ON transaction_ext_hotel(updated_on);",
                "idx_transaction_ext_import_file_updated_on ON transaction_ext_import_file(updated_on);",
                "idx_transaction_ext_installment_plan_updated_on ON transaction_ext_installment_plan(updated_on);",
                "idx_transaction_ext_installment_plan_options_updated_on ON transaction_ext_installment_plan_options(updated_on);",
                "idx_transaction_ext_ipp_updated_on ON transaction_ext_ipp(updated_on);",
                "idx_transaction_ext_iso_recon_updated_on ON transaction_ext_iso_recon(updated_on);",
                "idx_transaction_ext_onus_updated_on ON transaction_ext_onus(updated_on);",
                "idx_transaction_ext_payolution_updated_on ON transaction_ext_payolution(updated_on);",
                "idx_transaction_ext_pos_updated_on ON transaction_ext_pos(updated_on);",
                "idx_transaction_ext_risk_updated_on ON transaction_ext_risk(updated_on);",
                "idx_transaction_ext_signatures_updated_on ON transaction_ext_signatures(updated_on);",
                "idx_transaction_ext_surcharge_updated_on ON transaction_ext_surcharge(updated_on);",
                "idx_transaction_group_totals_updated_on ON transaction_group_totals(updated_on);",
                "idx_transaction_iso_references_updated_on ON transaction_iso_references(updated_on);",
                "idx_transaction_states_updated_on ON transaction_states(updated_on);",
                "idx_transaction_status_groups_updated_on ON transaction_status_groups(updated_on);",
                "idx_transaction_statuses_updated_on ON transaction_statuses(updated_on);",
                "idx_transaction_type_defaults_updated_on ON transaction_type_defaults(updated_on);",
                "idx_transaction_type_groups_updated_on ON transaction_type_groups(updated_on);",
                "idx_transaction_types_updated_on ON transaction_types(updated_on);",
                "idx_user_login_attempts_updated_on ON user_login_attempts(updated_on);",
                "idx_user_password_history_updated_on ON user_password_history(updated_on);",
                "idx_velocity_rules_updated_on ON velocity_rules(updated_on);"};


        for (int i = 0; i < lines.length; i++) {
            String[] split = lines[i].split(" ");
            String msg = "os_cmd_"+(i+1) + " = pt-online-schema-change --alter-foreign-keys-method=auto --critical-load Threads_running=100 --set-vars innodb_lock_wait_timeout=60,FOREIGN_KEY_CHECKS=0 --alter \"";
            msg+="ADD INDEX " + split[0] + " (updated_on)\" --alter-foreign-keys-method=auto t=" + split[2].split("\\(")[0];
            System.out.println(msg);

        }
    }
}
